version: '3'
services:
  clam_av:
    container_name: esign-clamav
    image: mk0x/docker-clamav
    restart: unless-stopped
    ports:
      - '3310:3310'
    expose:
      - '3310'
    networks:
      - esign-dev-network


networks:
  esign-dev-network:
    external: true
    