version: '3'

services:
  esign-services:
    build:
      context: /home/anduc/kltn/esign-services/.
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.api
    ports:
      - "4009:4009"
    expose:
      - "4009"
      


    

 