version: '3'

services:
  esign-clamav-1:
    build:
      context: /home/anduc/kltn/esign-clamav/.
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.clam
    expose:
      - "7009"
    networks:
      -  esign-dev-network
  
  esign-email:
    build:
      context: /home/anduc/kltn/esign-email-service/.
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.email
    expose:
      - "5009"
    networks:
      -  esign-dev-network

  esign-ipfs:
    build:
      context: /home/anduc/kltn/esign-ipfs-service/.
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.ipfs
    ports:
      - "6010:6010"
    expose:
      - "5009"
      - "6010"     
    networks:
      -  esign-dev-network 

networks:
  esign-dev-network:
    external: true




    

 