version: '3'

services:
  esign-email:
    build:
      context: /home/anduc/kltn/esign-email-service/.
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.email
    expose:
      - "5009"
    networks:
      -  esign-dev-network
      
networks:
  esign-dev-network:
    external: true
    
    


    

 