version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: esign-zookeeper
    volumes:
      - 'esign-zookeeper-data-1:/var/lib/zookeeper/data'
      - 'esign-zookeeper-log-1:/var/lib/zookeeper/log'
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - '2181:2181'
    expose:
      - '2181'
    networks:
      - esign-dev-network
  kafka:
    image: confluentinc/cp-kafka
    container_name: esign-kafka
    depends_on:
      - zookeeper
    volumes:
      - 'esign-kafka-data-1:/var/lib/kafka/data'
      - 'esign-kafka-log-1:/var/lib/kafka/log'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=EXTERNAL://localhost:9093,INTERNAL://kafka:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    ports:
      - '9093:9093'
    expose:
      - '9092'
    restart: always
    networks:
      - esign-dev-network

volumes:
  esign-zookeeper-data-1:
  esign-zookeeper-log-1:
  esign-kafka-data-1:
  esign-kafka-log-1:


networks:
  esign-dev-network:
    external: true