version: "3"

services:

  # Zookeeper
  zookeeper:
    image: "bitnami/zookeeper:3.5"
    container_name: zookeeper_bitnami
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami/zookeeper"
      - "zookeeper_logs:/bitnami/zookeeper/logs"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - esign-dev-network
    
  # Broker 1
  kafka1:
    image: "bitnami/kafka:2.4.1"
    container_name: kafka1_bitnami
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    volumes:
      - "kafka1_data:/bitnami/kafka/data"
      - "kafka1_data_log:/bitnami/kafka/logs"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://localhost:9093,INTERNAL://kafka1:9092
      - KAFKA_CFG_LISTENERS=EXTERNAL://:9093,INTERNAL://:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - esign-dev-network
   

  kafka2:
    image: "bitnami/kafka:2.4.1"
    container_name: kafka2_bitnami
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://localhost:9094,INTERNAL://kafka2:9092
      - KAFKA_CFG_LISTENERS=EXTERNAL://:9094,INTERNAL://:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - "kafka2_data:/bitnami/kafka/data"
      - "kafka2_data_log:/bitnami/kafka/logs"
    networks:
      - esign-dev-network
    restart: always
    mem_limit: 400m
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

  kafka3:
    image: "bitnami/kafka:2.4.1"
    container_name: kafka3_bitnami
    depends_on:
      - zookeeper
    ports:
      - "9095:9095"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://localhost:9095,INTERNAL://kafka3:9092
      - KAFKA_CFG_LISTENERS=EXTERNAL://:9095,INTERNAL://:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - "kafka3_data:/bitnami/kafka/data"
      - "kafka3_data_log:/bitnami/kafka/logs"
    networks:
      - esign-dev-network
    restart: always
    mem_limit: 400m
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

volumes:
  zookeeper_data:
    driver: local
  zookeeper_logs:
    driver: local
  kafka1_data:
    driver: local
  kafka1_data_log:
    driver: local
  kafka2_data:
    driver: local
  kafka2_data_log:
    driver: local
  kafka3_data:
    driver: local
  kafka3_data_log:
    driver: local

networks:
  esign-dev-network:
    external: true

