version: '3'

services:
  esign_postgre:
    image: postgres:12.1
    container_name: esign-postgre
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=esign
    volumes:
      - 'esign-postgre-data-1:/var/lib/postgresql/data'
    mem_limit: 256m
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      - esign-dev-network

volumes:
  esign-postgre-data-1:
    driver: local

networks:
  esign-dev-network:
    external: true