version: '3'


services:

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - "redis-data-dev:/data"
    command: redis-server --appendonly yes
    mem_limit: 128m
    networks:
      - esign-dev-network

volumes:
  redis-data-dev:
    driver: local

networks:
  esign-dev-network:
    external: true