version: '3'

services:
  esign-web-app:
    build:
      context: /home/anduc/kltn/esign-web/.
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.web
    ports:
      - "4008:4008"
    networks:
      -  esign-dev-network

networks:
  esign-dev-network:
    external: true
    
      