version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    volumes:
      - 'zookeeper-data:/var/lib/zookeeper/data'
      - 'zookeeper-log:/var/lib/zookeeper/log'
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - '2181:2181'
    networks:
      - kafka-net
    mem_limit: 256m

    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '3'

  kafka1:
    image: confluentinc/cp-kafka
    container_name: kafka1
    depends_on:
      - zookeeper
    volumes:
      - 'kafka1-data:/var/lib/kafka/data'
      - 'kafka1-log:/var/lib/kafka/log'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=EXTERNAL://localhost:9093,INTERNAL://kafka1:9092

      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL

    ports:
      - '9093:9093'
    restart: always
    mem_limit: 400m
    networks:
      - kafka-net

    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '3'

  kafka2:
    image: confluentinc/cp-kafka
    container_name: kafka2
    depends_on:
      - kafka1
    volumes:
      - 'kafka2-data:/var/lib/kafka/data'
      - 'kafka2-log:/var/lib/kafka/log'
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=EXTERNAL://localhost:9094,INTERNAL://kafka2:9092

      # - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092,PLAINTEXT_HOST://localhost:29093

      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL

    ports:
      - '9094:9094'
    restart: always
    mem_limit: 400m
    networks:
      - kafka-net

    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '3'

  kafka3:
    image: confluentinc/cp-kafka
    container_name: kafka3
    depends_on:
      - kafka2
    volumes:
      - 'kafka3-data:/var/lib/kafka/data'
      - 'kafka3-log:/var/lib/kafka/log'
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=EXTERNAL://localhost:9095,INTERNAL://kafka3:9092

      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    restart: always
    ports:
      - '9095:9095'
    mem_limit: 400m

    networks:
      - kafka-net

    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '3'

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - 'redis-data:/data'
    command: redis-server --appendonly yes
    mem_limit: 128m
    networks:
      - kafka-net

volumes:
  zookeeper-data:
  zookeeper-log:

  kafka1-data:
  kafka1-log:

  kafka2-data:
  kafka2-log:

  kafka3-data:
  kafka3-log:

  redis-data:

networks:
  kafka-net:
    driver: bridge
# version: "3"

# services:
#   zookeeper:
#     image: confluentinc/cp-zookeeper
#     container_name: zookeeper_main
#     volumes:
#       - "zookeeper_main_data:/var/lib/zookeeper/data"
#     environment:
#       - ZOOKEEPER_CLIENT_PORT=2181
#       - ZOOKEEPER_TICK_TIME=2000
#     ports:
#       - "2181:2181"
#     networks:
#       - kafka_main_net

#   kafka:
#     image: confluentinc/cp-kafka
#     container_name: kafka_main
#     depends_on:
#       - zookeeper
#     volumes:
#       - "kafka_main_data:/var/lib/kafka/data"
#     environment:
#       - KAFKA_BROKER_ID=1
#       - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

#       - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
#       - KAFKA_ADVERTISED_LISTENERS=EXTERNAL://localhost:9093,INTERNAL://kafka:9092

#       - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL

#     ports:
#       - "9093:9093"
#     networks:
#       - kafka_main_net

# volumes:
#   zookeeper_main_data:
#   kafka_main_data:

# networks:
#   kafka_main_net:
#     driver: bridge
